// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: clientPeer/proto/super_node.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_SETUP_EXIT  CommandType = 0
	CommandType_ROTATE_PEER CommandType = 1
	CommandType_RELAY_SETUP CommandType = 2
	CommandType_DISCONNECT  CommandType = 3
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "SETUP_EXIT",
		1: "ROTATE_PEER",
		2: "RELAY_SETUP",
		3: "DISCONNECT",
	}
	CommandType_value = map[string]int32{
		"SETUP_EXIT":  0,
		"ROTATE_PEER": 1,
		"RELAY_SETUP": 2,
		"DISCONNECT":  3,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_clientPeer_proto_super_node_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_clientPeer_proto_super_node_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_clientPeer_proto_super_node_proto_rawDescGZIP(), []int{0}
}

type ControlMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlMessage_AuthRequest
	//	*ControlMessage_AuthResponse
	//	*ControlMessage_PingRequest
	//	*ControlMessage_PongResponse
	//	*ControlMessage_Command
	//	*ControlMessage_CommandResponse
	//	*ControlMessage_InfoRequest
	//	*ControlMessage_InfoResponse
	Payload       isControlMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_clientPeer_proto_super_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_clientPeer_proto_super_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_clientPeer_proto_super_node_proto_rawDescGZIP(), []int{0}
}

func (x *ControlMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ControlMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ControlMessage) GetPayload() isControlMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlMessage) GetAuthRequest() *AuthRequest {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_AuthRequest); ok {
			return x.AuthRequest
		}
	}
	return nil
}

func (x *ControlMessage) GetAuthResponse() *AuthResponse {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_AuthResponse); ok {
			return x.AuthResponse
		}
	}
	return nil
}

func (x *ControlMessage) GetPingRequest() *PingRequest {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_PingRequest); ok {
			return x.PingRequest
		}
	}
	return nil
}

func (x *ControlMessage) GetPongResponse() *PongResponse {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_PongResponse); ok {
			return x.PongResponse
		}
	}
	return nil
}

func (x *ControlMessage) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *ControlMessage) GetCommandResponse() *CommandResponse {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_CommandResponse); ok {
			return x.CommandResponse
		}
	}
	return nil
}

func (x *ControlMessage) GetInfoRequest() *InfoRequest {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_InfoRequest); ok {
			return x.InfoRequest
		}
	}
	return nil
}

func (x *ControlMessage) GetInfoResponse() *InfoResponse {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_InfoResponse); ok {
			return x.InfoResponse
		}
	}
	return nil
}

type isControlMessage_Payload interface {
	isControlMessage_Payload()
}

type ControlMessage_AuthRequest struct {
	AuthRequest *AuthRequest `protobuf:"bytes,10,opt,name=auth_request,json=authRequest,proto3,oneof"`
}

type ControlMessage_AuthResponse struct {
	AuthResponse *AuthResponse `protobuf:"bytes,11,opt,name=auth_response,json=authResponse,proto3,oneof"`
}

type ControlMessage_PingRequest struct {
	PingRequest *PingRequest `protobuf:"bytes,12,opt,name=ping_request,json=pingRequest,proto3,oneof"`
}

type ControlMessage_PongResponse struct {
	PongResponse *PongResponse `protobuf:"bytes,13,opt,name=pong_response,json=pongResponse,proto3,oneof"`
}

type ControlMessage_Command struct {
	Command *Command `protobuf:"bytes,14,opt,name=command,proto3,oneof"`
}

type ControlMessage_CommandResponse struct {
	CommandResponse *CommandResponse `protobuf:"bytes,15,opt,name=command_response,json=commandResponse,proto3,oneof"`
}

type ControlMessage_InfoRequest struct {
	InfoRequest *InfoRequest `protobuf:"bytes,16,opt,name=info_request,json=infoRequest,proto3,oneof"`
}

type ControlMessage_InfoResponse struct {
	InfoResponse *InfoResponse `protobuf:"bytes,17,opt,name=info_response,json=infoResponse,proto3,oneof"`
}

func (*ControlMessage_AuthRequest) isControlMessage_Payload() {}

func (*ControlMessage_AuthResponse) isControlMessage_Payload() {}

func (*ControlMessage_PingRequest) isControlMessage_Payload() {}

func (*ControlMessage_PongResponse) isControlMessage_Payload() {}

func (*ControlMessage_Command) isControlMessage_Payload() {}

func (*ControlMessage_CommandResponse) isControlMessage_Payload() {}

func (*ControlMessage_InfoRequest) isControlMessage_Payload() {}

func (*ControlMessage_InfoResponse) isControlMessage_Payload() {}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"` // "client", "exit", "supernode"
	PubkeyB64     string                 `protobuf:"bytes,3,opt,name=pubkey_b64,json=pubkeyB64,proto3" json:"pubkey_b64,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	Signature     string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"` // Sign(peer_id||role||region||nonce)
	Nonce         string                 `protobuf:"bytes,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_clientPeer_proto_super_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clientPeer_proto_super_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_clientPeer_proto_super_node_proto_rawDescGZIP(), []int{1}
}

func (x *AuthRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *AuthRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AuthRequest) GetPubkeyB64() string {
	if x != nil {
		return x.PubkeyB64
	}
	return ""
}

func (x *AuthRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AuthRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *AuthRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_clientPeer_proto_super_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clientPeer_proto_super_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_clientPeer_proto_super_node_proto_rawDescGZIP(), []int{2}
}

func (x *AuthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuthResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PeerId        string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_clientPeer_proto_super_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clientPeer_proto_super_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_clientPeer_proto_super_node_proto_rawDescGZIP(), []int{3}
}

func (x *PingRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PingRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type PongResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Timestamp         int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	OriginalTimestamp int64                  `protobuf:"varint,2,opt,name=original_timestamp,json=originalTimestamp,proto3" json:"original_timestamp,omitempty"`
	PeerId            string                 `protobuf:"bytes,3,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PongResponse) Reset() {
	*x = PongResponse{}
	mi := &file_clientPeer_proto_super_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongResponse) ProtoMessage() {}

func (x *PongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clientPeer_proto_super_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongResponse.ProtoReflect.Descriptor instead.
func (*PongResponse) Descriptor() ([]byte, []int) {
	return file_clientPeer_proto_super_node_proto_rawDescGZIP(), []int{4}
}

func (x *PongResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PongResponse) GetOriginalTimestamp() int64 {
	if x != nil {
		return x.OriginalTimestamp
	}
	return 0
}

func (x *PongResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Type          CommandType            `protobuf:"varint,2,opt,name=type,proto3,enum=control.CommandType" json:"type,omitempty"`
	Payload       map[string]string      `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_clientPeer_proto_super_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_clientPeer_proto_super_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_clientPeer_proto_super_node_proto_rawDescGZIP(), []int{5}
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Command) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_SETUP_EXIT
}

func (x *Command) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Result        map[string]string      `protobuf:"bytes,4,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_clientPeer_proto_super_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clientPeer_proto_super_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_clientPeer_proto_super_node_proto_rawDescGZIP(), []int{6}
}

func (x *CommandResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommandResponse) GetResult() map[string]string {
	if x != nil {
		return x.Result
	}
	return nil
}

type InfoRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PeerId          string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	RequestedFields []string               `protobuf:"bytes,2,rep,name=requested_fields,json=requestedFields,proto3" json:"requested_fields,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_clientPeer_proto_super_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clientPeer_proto_super_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_clientPeer_proto_super_node_proto_rawDescGZIP(), []int{7}
}

func (x *InfoRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *InfoRequest) GetRequestedFields() []string {
	if x != nil {
		return x.RequestedFields
	}
	return nil
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Info          map[string]string      `protobuf:"bytes,2,rep,name=info,proto3" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_clientPeer_proto_super_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clientPeer_proto_super_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_clientPeer_proto_super_node_proto_rawDescGZIP(), []int{8}
}

func (x *InfoResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *InfoResponse) GetInfo() map[string]string {
	if x != nil {
		return x.Info
	}
	return nil
}

// Inter-SuperNode communication
type RequestExitPeerRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ClientId              string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Region                string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	RequestingSupernodeId string                 `protobuf:"bytes,3,opt,name=requesting_supernode_id,json=requestingSupernodeId,proto3" json:"requesting_supernode_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RequestExitPeerRequest) Reset() {
	*x = RequestExitPeerRequest{}
	mi := &file_clientPeer_proto_super_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestExitPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestExitPeerRequest) ProtoMessage() {}

func (x *RequestExitPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clientPeer_proto_super_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestExitPeerRequest.ProtoReflect.Descriptor instead.
func (*RequestExitPeerRequest) Descriptor() ([]byte, []int) {
	return file_clientPeer_proto_super_node_proto_rawDescGZIP(), []int{9}
}

func (x *RequestExitPeerRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RequestExitPeerRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RequestExitPeerRequest) GetRequestingSupernodeId() string {
	if x != nil {
		return x.RequestingSupernodeId
	}
	return ""
}

type RequestExitPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ExitPeer      *ExitPeerInfo          `protobuf:"bytes,3,opt,name=exit_peer,json=exitPeer,proto3" json:"exit_peer,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestExitPeerResponse) Reset() {
	*x = RequestExitPeerResponse{}
	mi := &file_clientPeer_proto_super_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestExitPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestExitPeerResponse) ProtoMessage() {}

func (x *RequestExitPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clientPeer_proto_super_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestExitPeerResponse.ProtoReflect.Descriptor instead.
func (*RequestExitPeerResponse) Descriptor() ([]byte, []int) {
	return file_clientPeer_proto_super_node_proto_rawDescGZIP(), []int{10}
}

func (x *RequestExitPeerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RequestExitPeerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RequestExitPeerResponse) GetExitPeer() *ExitPeerInfo {
	if x != nil {
		return x.ExitPeer
	}
	return nil
}

func (x *RequestExitPeerResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ExitPeerInfo struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	PeerId                   string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	PublicKey                string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Endpoint                 string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"` // IP:port
	AllowedIps               []string               `protobuf:"bytes,4,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	SupportsDirectConnection bool                   `protobuf:"varint,5,opt,name=supports_direct_connection,json=supportsDirectConnection,proto3" json:"supports_direct_connection,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ExitPeerInfo) Reset() {
	*x = ExitPeerInfo{}
	mi := &file_clientPeer_proto_super_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitPeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitPeerInfo) ProtoMessage() {}

func (x *ExitPeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_clientPeer_proto_super_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitPeerInfo.ProtoReflect.Descriptor instead.
func (*ExitPeerInfo) Descriptor() ([]byte, []int) {
	return file_clientPeer_proto_super_node_proto_rawDescGZIP(), []int{11}
}

func (x *ExitPeerInfo) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *ExitPeerInfo) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *ExitPeerInfo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ExitPeerInfo) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *ExitPeerInfo) GetSupportsDirectConnection() bool {
	if x != nil {
		return x.SupportsDirectConnection
	}
	return false
}

var File_clientPeer_proto_super_node_proto protoreflect.FileDescriptor

const file_clientPeer_proto_super_node_proto_rawDesc = "" +
	"\n" +
	"!clientPeer/proto/super_node.proto\x12\acontrol\"\xb8\x04\n" +
	"\x0eControlMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x129\n" +
	"\fauth_request\x18\n" +
	" \x01(\v2\x14.control.AuthRequestH\x00R\vauthRequest\x12<\n" +
	"\rauth_response\x18\v \x01(\v2\x15.control.AuthResponseH\x00R\fauthResponse\x129\n" +
	"\fping_request\x18\f \x01(\v2\x14.control.PingRequestH\x00R\vpingRequest\x12<\n" +
	"\rpong_response\x18\r \x01(\v2\x15.control.PongResponseH\x00R\fpongResponse\x12,\n" +
	"\acommand\x18\x0e \x01(\v2\x10.control.CommandH\x00R\acommand\x12E\n" +
	"\x10command_response\x18\x0f \x01(\v2\x18.control.CommandResponseH\x00R\x0fcommandResponse\x129\n" +
	"\finfo_request\x18\x10 \x01(\v2\x14.control.InfoRequestH\x00R\vinfoRequest\x12<\n" +
	"\rinfo_response\x18\x11 \x01(\v2\x15.control.InfoResponseH\x00R\finfoResponseB\t\n" +
	"\apayload\"\xa5\x01\n" +
	"\vAuthRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"pubkey_b64\x18\x03 \x01(\tR\tpubkeyB64\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\tR\x05nonce\"a\n" +
	"\fAuthResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"D\n" +
	"\vPingRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\"t\n" +
	"\fPongResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12-\n" +
	"\x12original_timestamp\x18\x02 \x01(\x03R\x11originalTimestamp\x12\x17\n" +
	"\apeer_id\x18\x03 \x01(\tR\x06peerId\"\xc7\x01\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.control.CommandTypeR\x04type\x127\n" +
	"\apayload\x18\x03 \x03(\v2\x1d.control.Command.PayloadEntryR\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdd\x01\n" +
	"\x0fCommandResponse\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12<\n" +
	"\x06result\x18\x04 \x03(\v2$.control.CommandResponse.ResultEntryR\x06result\x1a9\n" +
	"\vResultEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\vInfoRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12)\n" +
	"\x10requested_fields\x18\x02 \x03(\tR\x0frequestedFields\"\x95\x01\n" +
	"\fInfoResponse\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x123\n" +
	"\x04info\x18\x02 \x03(\v2\x1f.control.InfoResponse.InfoEntryR\x04info\x1a7\n" +
	"\tInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x01\n" +
	"\x16RequestExitPeerRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x126\n" +
	"\x17requesting_supernode_id\x18\x03 \x01(\tR\x15requestingSupernodeId\"\xa0\x01\n" +
	"\x17RequestExitPeerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\texit_peer\x18\x03 \x01(\v2\x15.control.ExitPeerInfoR\bexitPeer\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"\xc1\x01\n" +
	"\fExitPeerInfo\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vallowed_ips\x18\x04 \x03(\tR\n" +
	"allowedIps\x12<\n" +
	"\x1asupports_direct_connection\x18\x05 \x01(\bR\x18supportsDirectConnection*O\n" +
	"\vCommandType\x12\x0e\n" +
	"\n" +
	"SETUP_EXIT\x10\x00\x12\x0f\n" +
	"\vROTATE_PEER\x10\x01\x12\x0f\n" +
	"\vRELAY_SETUP\x10\x02\x12\x0e\n" +
	"\n" +
	"DISCONNECT\x10\x032`\n" +
	"\rControlStream\x12O\n" +
	"\x17PersistentControlStream\x12\x17.control.ControlMessage\x1a\x17.control.ControlMessage(\x010\x012a\n" +
	"\tSuperNode\x12T\n" +
	"\x0fRequestExitPeer\x12\x1f.control.RequestExitPeerRequest\x1a .control.RequestExitPeerResponseB\x19Z\x17myDvpn/clientPeer/protob\x06proto3"

var (
	file_clientPeer_proto_super_node_proto_rawDescOnce sync.Once
	file_clientPeer_proto_super_node_proto_rawDescData []byte
)

func file_clientPeer_proto_super_node_proto_rawDescGZIP() []byte {
	file_clientPeer_proto_super_node_proto_rawDescOnce.Do(func() {
		file_clientPeer_proto_super_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clientPeer_proto_super_node_proto_rawDesc), len(file_clientPeer_proto_super_node_proto_rawDesc)))
	})
	return file_clientPeer_proto_super_node_proto_rawDescData
}

var file_clientPeer_proto_super_node_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_clientPeer_proto_super_node_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_clientPeer_proto_super_node_proto_goTypes = []any{
	(CommandType)(0),                // 0: control.CommandType
	(*ControlMessage)(nil),          // 1: control.ControlMessage
	(*AuthRequest)(nil),             // 2: control.AuthRequest
	(*AuthResponse)(nil),            // 3: control.AuthResponse
	(*PingRequest)(nil),             // 4: control.PingRequest
	(*PongResponse)(nil),            // 5: control.PongResponse
	(*Command)(nil),                 // 6: control.Command
	(*CommandResponse)(nil),         // 7: control.CommandResponse
	(*InfoRequest)(nil),             // 8: control.InfoRequest
	(*InfoResponse)(nil),            // 9: control.InfoResponse
	(*RequestExitPeerRequest)(nil),  // 10: control.RequestExitPeerRequest
	(*RequestExitPeerResponse)(nil), // 11: control.RequestExitPeerResponse
	(*ExitPeerInfo)(nil),            // 12: control.ExitPeerInfo
	nil,                             // 13: control.Command.PayloadEntry
	nil,                             // 14: control.CommandResponse.ResultEntry
	nil,                             // 15: control.InfoResponse.InfoEntry
}
var file_clientPeer_proto_super_node_proto_depIdxs = []int32{
	2,  // 0: control.ControlMessage.auth_request:type_name -> control.AuthRequest
	3,  // 1: control.ControlMessage.auth_response:type_name -> control.AuthResponse
	4,  // 2: control.ControlMessage.ping_request:type_name -> control.PingRequest
	5,  // 3: control.ControlMessage.pong_response:type_name -> control.PongResponse
	6,  // 4: control.ControlMessage.command:type_name -> control.Command
	7,  // 5: control.ControlMessage.command_response:type_name -> control.CommandResponse
	8,  // 6: control.ControlMessage.info_request:type_name -> control.InfoRequest
	9,  // 7: control.ControlMessage.info_response:type_name -> control.InfoResponse
	0,  // 8: control.Command.type:type_name -> control.CommandType
	13, // 9: control.Command.payload:type_name -> control.Command.PayloadEntry
	14, // 10: control.CommandResponse.result:type_name -> control.CommandResponse.ResultEntry
	15, // 11: control.InfoResponse.info:type_name -> control.InfoResponse.InfoEntry
	12, // 12: control.RequestExitPeerResponse.exit_peer:type_name -> control.ExitPeerInfo
	1,  // 13: control.ControlStream.PersistentControlStream:input_type -> control.ControlMessage
	10, // 14: control.SuperNode.RequestExitPeer:input_type -> control.RequestExitPeerRequest
	1,  // 15: control.ControlStream.PersistentControlStream:output_type -> control.ControlMessage
	11, // 16: control.SuperNode.RequestExitPeer:output_type -> control.RequestExitPeerResponse
	15, // [15:17] is the sub-list for method output_type
	13, // [13:15] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_clientPeer_proto_super_node_proto_init() }
func file_clientPeer_proto_super_node_proto_init() {
	if File_clientPeer_proto_super_node_proto != nil {
		return
	}
	file_clientPeer_proto_super_node_proto_msgTypes[0].OneofWrappers = []any{
		(*ControlMessage_AuthRequest)(nil),
		(*ControlMessage_AuthResponse)(nil),
		(*ControlMessage_PingRequest)(nil),
		(*ControlMessage_PongResponse)(nil),
		(*ControlMessage_Command)(nil),
		(*ControlMessage_CommandResponse)(nil),
		(*ControlMessage_InfoRequest)(nil),
		(*ControlMessage_InfoResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clientPeer_proto_super_node_proto_rawDesc), len(file_clientPeer_proto_super_node_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_clientPeer_proto_super_node_proto_goTypes,
		DependencyIndexes: file_clientPeer_proto_super_node_proto_depIdxs,
		EnumInfos:         file_clientPeer_proto_super_node_proto_enumTypes,
		MessageInfos:      file_clientPeer_proto_super_node_proto_msgTypes,
	}.Build()
	File_clientPeer_proto_super_node_proto = out.File
	file_clientPeer_proto_super_node_proto_goTypes = nil
	file_clientPeer_proto_super_node_proto_depIdxs = nil
}
