// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: base/proto/base.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterSuperNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	SupernodeId   string                 `protobuf:"bytes,2,opt,name=supernode_id,json=supernodeId,proto3" json:"supernode_id,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	CurrentLoad   int32                  `protobuf:"varint,5,opt,name=current_load,json=currentLoad,proto3" json:"current_load,omitempty"` // Number of active peers
	MaxCapacity   int32                  `protobuf:"varint,6,opt,name=max_capacity,json=maxCapacity,proto3" json:"max_capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSuperNodeRequest) Reset() {
	*x = RegisterSuperNodeRequest{}
	mi := &file_base_proto_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSuperNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSuperNodeRequest) ProtoMessage() {}

func (x *RegisterSuperNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSuperNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterSuperNodeRequest) Descriptor() ([]byte, []int) {
	return file_base_proto_base_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterSuperNodeRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RegisterSuperNodeRequest) GetSupernodeId() string {
	if x != nil {
		return x.SupernodeId
	}
	return ""
}

func (x *RegisterSuperNodeRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterSuperNodeRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RegisterSuperNodeRequest) GetCurrentLoad() int32 {
	if x != nil {
		return x.CurrentLoad
	}
	return 0
}

func (x *RegisterSuperNodeRequest) GetMaxCapacity() int32 {
	if x != nil {
		return x.MaxCapacity
	}
	return 0
}

type RegisterSuperNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSuperNodeResponse) Reset() {
	*x = RegisterSuperNodeResponse{}
	mi := &file_base_proto_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSuperNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSuperNodeResponse) ProtoMessage() {}

func (x *RegisterSuperNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSuperNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterSuperNodeResponse) Descriptor() ([]byte, []int) {
	return file_base_proto_base_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterSuperNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterSuperNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RequestExitRegionRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TargetRegion          string                 `protobuf:"bytes,1,opt,name=target_region,json=targetRegion,proto3" json:"target_region,omitempty"`
	RequestingSupernodeId string                 `protobuf:"bytes,2,opt,name=requesting_supernode_id,json=requestingSupernodeId,proto3" json:"requesting_supernode_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RequestExitRegionRequest) Reset() {
	*x = RequestExitRegionRequest{}
	mi := &file_base_proto_base_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestExitRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestExitRegionRequest) ProtoMessage() {}

func (x *RequestExitRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_base_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestExitRegionRequest.ProtoReflect.Descriptor instead.
func (*RequestExitRegionRequest) Descriptor() ([]byte, []int) {
	return file_base_proto_base_proto_rawDescGZIP(), []int{2}
}

func (x *RequestExitRegionRequest) GetTargetRegion() string {
	if x != nil {
		return x.TargetRegion
	}
	return ""
}

func (x *RequestExitRegionRequest) GetRequestingSupernodeId() string {
	if x != nil {
		return x.RequestingSupernodeId
	}
	return ""
}

type RequestExitRegionResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CandidateSupernodes []*SuperNodeInfo       `protobuf:"bytes,1,rep,name=candidate_supernodes,json=candidateSupernodes,proto3" json:"candidate_supernodes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RequestExitRegionResponse) Reset() {
	*x = RequestExitRegionResponse{}
	mi := &file_base_proto_base_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestExitRegionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestExitRegionResponse) ProtoMessage() {}

func (x *RequestExitRegionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_base_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestExitRegionResponse.ProtoReflect.Descriptor instead.
func (*RequestExitRegionResponse) Descriptor() ([]byte, []int) {
	return file_base_proto_base_proto_rawDescGZIP(), []int{3}
}

func (x *RequestExitRegionResponse) GetCandidateSupernodes() []*SuperNodeInfo {
	if x != nil {
		return x.CandidateSupernodes
	}
	return nil
}

type ListSuperNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSuperNodesRequest) Reset() {
	*x = ListSuperNodesRequest{}
	mi := &file_base_proto_base_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSuperNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSuperNodesRequest) ProtoMessage() {}

func (x *ListSuperNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_base_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSuperNodesRequest.ProtoReflect.Descriptor instead.
func (*ListSuperNodesRequest) Descriptor() ([]byte, []int) {
	return file_base_proto_base_proto_rawDescGZIP(), []int{4}
}

type ListSuperNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Supernodes    []*SuperNodeInfo       `protobuf:"bytes,1,rep,name=supernodes,proto3" json:"supernodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSuperNodesResponse) Reset() {
	*x = ListSuperNodesResponse{}
	mi := &file_base_proto_base_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSuperNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSuperNodesResponse) ProtoMessage() {}

func (x *ListSuperNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_base_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSuperNodesResponse.ProtoReflect.Descriptor instead.
func (*ListSuperNodesResponse) Descriptor() ([]byte, []int) {
	return file_base_proto_base_proto_rawDescGZIP(), []int{5}
}

func (x *ListSuperNodesResponse) GetSupernodes() []*SuperNodeInfo {
	if x != nil {
		return x.Supernodes
	}
	return nil
}

type SuperNodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SupernodeId   string                 `protobuf:"bytes,1,opt,name=supernode_id,json=supernodeId,proto3" json:"supernode_id,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	CurrentLoad   int32                  `protobuf:"varint,5,opt,name=current_load,json=currentLoad,proto3" json:"current_load,omitempty"`
	MaxCapacity   int32                  `protobuf:"varint,6,opt,name=max_capacity,json=maxCapacity,proto3" json:"max_capacity,omitempty"`
	LastHeartbeat int64                  `protobuf:"varint,7,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuperNodeInfo) Reset() {
	*x = SuperNodeInfo{}
	mi := &file_base_proto_base_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuperNodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuperNodeInfo) ProtoMessage() {}

func (x *SuperNodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_base_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuperNodeInfo.ProtoReflect.Descriptor instead.
func (*SuperNodeInfo) Descriptor() ([]byte, []int) {
	return file_base_proto_base_proto_rawDescGZIP(), []int{6}
}

func (x *SuperNodeInfo) GetSupernodeId() string {
	if x != nil {
		return x.SupernodeId
	}
	return ""
}

func (x *SuperNodeInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *SuperNodeInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *SuperNodeInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SuperNodeInfo) GetCurrentLoad() int32 {
	if x != nil {
		return x.CurrentLoad
	}
	return 0
}

func (x *SuperNodeInfo) GetMaxCapacity() int32 {
	if x != nil {
		return x.MaxCapacity
	}
	return 0
}

func (x *SuperNodeInfo) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

var File_base_proto_base_proto protoreflect.FileDescriptor

const file_base_proto_base_proto_rawDesc = "" +
	"\n" +
	"\x15base/proto/base.proto\x12\x04base\"\xce\x01\n" +
	"\x18RegisterSuperNodeRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12!\n" +
	"\fsupernode_id\x18\x02 \x01(\tR\vsupernodeId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12!\n" +
	"\fcurrent_load\x18\x05 \x01(\x05R\vcurrentLoad\x12!\n" +
	"\fmax_capacity\x18\x06 \x01(\x05R\vmaxCapacity\"O\n" +
	"\x19RegisterSuperNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"w\n" +
	"\x18RequestExitRegionRequest\x12#\n" +
	"\rtarget_region\x18\x01 \x01(\tR\ftargetRegion\x126\n" +
	"\x17requesting_supernode_id\x18\x02 \x01(\tR\x15requestingSupernodeId\"c\n" +
	"\x19RequestExitRegionResponse\x12F\n" +
	"\x14candidate_supernodes\x18\x01 \x03(\v2\x13.base.SuperNodeInfoR\x13candidateSupernodes\"\x17\n" +
	"\x15ListSuperNodesRequest\"M\n" +
	"\x16ListSuperNodesResponse\x123\n" +
	"\n" +
	"supernodes\x18\x01 \x03(\v2\x13.base.SuperNodeInfoR\n" +
	"supernodes\"\xea\x01\n" +
	"\rSuperNodeInfo\x12!\n" +
	"\fsupernode_id\x18\x01 \x01(\tR\vsupernodeId\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12!\n" +
	"\fcurrent_load\x18\x05 \x01(\x05R\vcurrentLoad\x12!\n" +
	"\fmax_capacity\x18\x06 \x01(\x05R\vmaxCapacity\x12%\n" +
	"\x0elast_heartbeat\x18\a \x01(\x03R\rlastHeartbeat2\x83\x02\n" +
	"\bBaseNode\x12T\n" +
	"\x11RegisterSuperNode\x12\x1e.base.RegisterSuperNodeRequest\x1a\x1f.base.RegisterSuperNodeResponse\x12T\n" +
	"\x11RequestExitRegion\x12\x1e.base.RequestExitRegionRequest\x1a\x1f.base.RequestExitRegionResponse\x12K\n" +
	"\x0eListSuperNodes\x12\x1b.base.ListSuperNodesRequest\x1a\x1c.base.ListSuperNodesResponseB\x13Z\x11myDvpn/base/protob\x06proto3"

var (
	file_base_proto_base_proto_rawDescOnce sync.Once
	file_base_proto_base_proto_rawDescData []byte
)

func file_base_proto_base_proto_rawDescGZIP() []byte {
	file_base_proto_base_proto_rawDescOnce.Do(func() {
		file_base_proto_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_proto_base_proto_rawDesc), len(file_base_proto_base_proto_rawDesc)))
	})
	return file_base_proto_base_proto_rawDescData
}

var file_base_proto_base_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_base_proto_base_proto_goTypes = []any{
	(*RegisterSuperNodeRequest)(nil),  // 0: base.RegisterSuperNodeRequest
	(*RegisterSuperNodeResponse)(nil), // 1: base.RegisterSuperNodeResponse
	(*RequestExitRegionRequest)(nil),  // 2: base.RequestExitRegionRequest
	(*RequestExitRegionResponse)(nil), // 3: base.RequestExitRegionResponse
	(*ListSuperNodesRequest)(nil),     // 4: base.ListSuperNodesRequest
	(*ListSuperNodesResponse)(nil),    // 5: base.ListSuperNodesResponse
	(*SuperNodeInfo)(nil),             // 6: base.SuperNodeInfo
}
var file_base_proto_base_proto_depIdxs = []int32{
	6, // 0: base.RequestExitRegionResponse.candidate_supernodes:type_name -> base.SuperNodeInfo
	6, // 1: base.ListSuperNodesResponse.supernodes:type_name -> base.SuperNodeInfo
	0, // 2: base.BaseNode.RegisterSuperNode:input_type -> base.RegisterSuperNodeRequest
	2, // 3: base.BaseNode.RequestExitRegion:input_type -> base.RequestExitRegionRequest
	4, // 4: base.BaseNode.ListSuperNodes:input_type -> base.ListSuperNodesRequest
	1, // 5: base.BaseNode.RegisterSuperNode:output_type -> base.RegisterSuperNodeResponse
	3, // 6: base.BaseNode.RequestExitRegion:output_type -> base.RequestExitRegionResponse
	5, // 7: base.BaseNode.ListSuperNodes:output_type -> base.ListSuperNodesResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_base_proto_base_proto_init() }
func file_base_proto_base_proto_init() {
	if File_base_proto_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_proto_base_proto_rawDesc), len(file_base_proto_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_base_proto_base_proto_goTypes,
		DependencyIndexes: file_base_proto_base_proto_depIdxs,
		MessageInfos:      file_base_proto_base_proto_msgTypes,
	}.Build()
	File_base_proto_base_proto = out.File
	file_base_proto_base_proto_goTypes = nil
	file_base_proto_base_proto_depIdxs = nil
}
